repos:

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ['--config=.flake8']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: debug-statements
      - id: check-yaml
      - id: requirements-txt-fixer
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: python
        'types': [python]
        pass_filenames: false

  - repo: local
    hooks:
      - id: poetry_export
        name: poetry_export
        entry: poetry export --without-hashes -o requirements.txt
        language: system
        pass_filenames: false
