name: Publish Python Package

on:
  release:
    types:
      - created

jobs:
  publish:
    if: github.event_name == 'release'
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for PyPI trusted publishing

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install poetry
      run: |
        pip install poetry

    - name: Install dependencies using poetry
      run: |
        poetry install

    - name: Check code with ruff
      run: |
        poetry run ruff check .

    - name: Build and publish on PyPI
      run: |
        echo "Build package version $VERSION"
        poetry version $VERSION
        poetry publish --build --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
      env:
        VERSION: ${{ github.event.release.tag_name }}
